version: "3.7"
services:
  db-laravel:
    image: postgres:latest
    container_name: db-laravel
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: db-laravel
    networks:
      - laravel-test

  laravel-kafka:
    build:
      args:
        user: jose_santos
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: laravel-test
    container_name: laravel-test-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-test
    depends_on:
      - db-laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-test-nginx
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - laravel-test

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: laravel-test-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - laravel-test

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: laravel-test-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - laravel-test



networks:
  laravel-test:
    driver: bridge
